# Generated by Django 5.0.3 on 2024-04-03 19:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Kolor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=200, unique=True)),
            ],
            options={
                'verbose_name': 'kolor',
                'verbose_name_plural': 'kolory',
            },
        ),
        migrations.CreateModel(
            name='Rozmiar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=200, unique=True)),
            ],
            options={
                'verbose_name': 'rozmiar',
                'verbose_name_plural': 'rozmiary',
            },
        ),
        migrations.CreateModel(
            name='TypProduktu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'typ produktu',
                'verbose_name_plural': 'typy produktów',
            },
        ),
        migrations.CreateModel(
            name='Dostawa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=200)),
                ('created_on', models.DateTimeField(verbose_name='data dostawy')),
                ('created_by', models.ForeignKey(blank=True, default=None, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'dostawa',
                'verbose_name_plural': 'dostawy',
            },
        ),
        migrations.CreateModel(
            name='Produkt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=200)),
                ('is_active', models.BooleanField(default=True, verbose_name='aktywny')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='data utworzenia')),
                ('dlugosc', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('szerokosc', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('wysokosc', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='wysokość')),
                ('waga', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('cena', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('created_by', models.ForeignKey(blank=True, default=None, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('kolor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sklep.kolor')),
                ('rozmiar', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sklep.rozmiar')),
                ('typ_produktu', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sklep.typproduktu')),
            ],
            options={
                'verbose_name': 'produkt',
                'verbose_name_plural': 'produkty',
            },
        ),
        migrations.CreateModel(
            name='AtrybutTypuProduktu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(editable=False, max_length=200)),
                ('field', models.CharField(editable=False, max_length=200)),
                ('is_visible', models.BooleanField(default=True, verbose_name='widoczny')),
                ('typ_produktu', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='attrs', to='sklep.typproduktu')),
            ],
            options={
                'verbose_name': 'typ produktu (atrybut)',
                'verbose_name_plural': 'typ produktu (atrybuty)',
            },
        ),
    ]
